In [1]:
#Decision Tree Regression

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
dataset = pd.read_csv('processed.csv')

dataset.head()

,Unnamed: 0,price,gearbox,powerPS,kilometer,monthOfRegistration,notRepairedDamage,brand_alfa_romeo,brand_audi,brand_bmw,...,model_x_reihe,model_x_trail,model_x_type,model_xc_reihe,model_yaris,model_yeti,model_ypsilon,model_z_reihe,model_zafira,yearOfRegistration
0,1,18300,1,190,125000,5,1,0,1,0,...,0,0,0,0,0,0,0,0,0,5
1,3,1500,1,75,150000,6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,15
2,4,3600,1,69,90000,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
3,5,650,1,102,150000,10,1,0,0,1,...,0,0,0,0,0,0,0,0,0,21
4,6,2200,1,109,150000,8,0,0,0,0,...,0,0,0,0,0,0,0,0,0,12

In [2]:

X = dataset.iloc[:,2:].values 
y = dataset.iloc[:,1].values

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

#Normalizing the features
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

#Create and Fit a Regressor Object
from sklearn.tree import DecisionTreeRegressor
regObj = DecisionTreeRegressor()
regObj.fit(X_train,y_train) 
y_pred = regObj.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_pred, y_test)
print(mse)

print(y_pred)
print(y_test)

52972731795782.89
[ 4200.  2300. 16990. ... 25987. 52900.  1900.]
[ 3240  1800 18950 ... 25987 59900  8750]

In [ ]:


# #Visualizing Results of Decision Tree Regression
# plt.scatter(X, y, color='red')
# plt.plot(X, regObj.predict(X), color='blue')
# plt.title('Results')
# plt.xlabel('Level')
# plt.ylabel('Salary')
# plt.show()

# # Visualizing the Decision Tree Regression in higher resolution
# X_grid = np.arange(min(X), max(X), 0.01)
# X_grid = X_grid.reshape((len(X_grid), 1))
# plt.scatter(X, y, color = 'red')
# plt.plot(X_grid, regObj.predict(X_grid), color = 'blue')
# plt.title('Results')
# plt.xlabel('Level')
# plt.ylabel('Salary')
# plt.show()


# #Predicting with Linear Model
# print(regObj.predict([[8.33]]))