In [7]:
#Decision Tree Regression

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Loading the dataset
try:
  dataset = pd.read_csv('processed.csv')
except:
  dataset = pd.read_csv('drive/My Drive/processed.csv')

dataset.head()

   Unnamed: 0  log_price  gearbox  ...  model_z_reihe  model_zafira  years_old
0           1   4.262451        1  ...              0             0          5
1           3   3.176091        1  ...              0             0         15
2           4   3.556303        1  ...              0             0          8
3           5   2.812913        1  ...              0             0         21
4           6   3.342423        1  ...              0             0         12

[5 rows x 309 columns]

In [8]:

X = dataset.iloc[:,2:].values 
y = dataset.iloc[:,1].values

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

#Normalizing the features
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

#Create and Fit a Regressor Object
from sklearn.tree import DecisionTreeRegressor
regObj = DecisionTreeRegressor()
regObj.fit(X_train,y_train) 
y_pred = regObj.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(mse)

print(y_pred)
print(y_test)

0.05215963198602538
[3.47697647 4.39776626 2.92941893 ... 3.12915071 3.67209786 3.35378509]
[3.79927161 4.39776626 2.74036269 ... 3.11394335 3.30081279 3.11394335]

In [9]:
mse_exp = mean_squared_error(10**y_test, 10**y_pred)
print(mse_exp)
print(10**y_pred)
print(10**y_test)

63238336.62957917
[ 2999.         24990.           850.         ...  1346.32746688
  4700.          2258.31795813]
[ 6299. 24990.   550. ...  1300.  1999.  1300.]

In [0]:


# #Visualizing Results of Decision Tree Regression
# plt.scatter(X, y, color='red')
# plt.plot(X, regObj.predict(X), color='blue')
# plt.title('Results')
# plt.xlabel('Level')
# plt.ylabel('Salary')
# plt.show()

# # Visualizing the Decision Tree Regression in higher resolution
# X_grid = np.arange(min(X), max(X), 0.01)
# X_grid = X_grid.reshape((len(X_grid), 1))
# plt.scatter(X, y, color = 'red')
# plt.plot(X_grid, regObj.predict(X_grid), color = 'blue')
# plt.title('Results')
# plt.xlabel('Level')
# plt.ylabel('Salary')
# plt.show()


# #Predicting with Linear Model
# print(regObj.predict([[8.33]]))